name: Generator Auto HOME Tgram
on:
  schedule:
    - cron: "0 */2 * * *"  # Runs every hour
  workflow_dispatch:  # Optional: keep for manual testing

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Generate key on Linux
        run: |
          ACCOUNT=0
          KEY=2
          MAIL=emailfake
          KEY_TYPE=--key
          BRANCH=main

          git clone -b ${BRANCH} https://github.com/373262/EKey.git
          cd EKey

          sudo apt update
          sudo apt install -y python3-pip python3-venv
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

          if [[ ${ACCOUNT} -ne 0 && ${KEY} -ne 0 ]]; then
            seq 1 ${ACCOUNT} | xargs -I {} -P ${ACCOUNT} python3 main.py --silent --chrome --account --email-api ${MAIL} --vktoken ${{ secrets.VKTOKEN }} --vktoken2 ${{ secrets.VKTOKEN2 }} --vkgroupid ${{ secrets.VKGROUPID }} --token ${{ secrets.TOKEN }} --skip-webdriver-menu --skip-update-check --no-logo --disable-progress-bar &
            seq 1 ${KEY} | xargs -I {} -P ${KEY} python3 main.py --chrome --key --email-api ${MAIL} --skip-webdriver-menu --skip-update-check --no-logo --disable-progress-bar
            wait
            echo "Account:" >> $GITHUB_STEP_SUMMARY
            cat ./*ACCOUNTS.txt >> $GITHUB_STEP_SUMMARY
            echo -e "\nKey:" >> $GITHUB_STEP_SUMMARY
            cat ./*KEYS.txt >> $GITHUB_STEP_SUMMARY
          elif [[ ${ACCOUNT} -ne 0 ]]; then
            seq 1 ${ACCOUNT} | xargs -I {} -P ${ACCOUNT} python3 main.py --silent --chrome --account --email-api ${MAIL} --vktoken ${{ secrets.VKTOKEN }} --vktoken2 ${{ secrets.VKTOKEN2 }} --vkgroupid ${{ secrets.VKGROUPID }} --token ${{ secrets.TOKEN }} --skip-webdriver-menu --skip-update-check --no-logo --disable-progress-bar
            echo -e "\nAccount:" >> $GITHUB_STEP_SUMMARY
            cat ./*ACCOUNTS.txt >> $GITHUB_STEP_SUMMARY
          elif [[ ${KEY} -ne 0 ]]; then
            seq 1 ${KEY} | xargs -I {} -P ${KEY} python3 main.py --silent --chrome --key --email-api ${MAIL} --vktoken ${{ secrets.VKTOKEN }} --vktoken2 ${{ secrets.VKTOKEN2 }} --vkgroupid ${{ secrets.VKGROUPID }} --token ${{ secrets.TOKEN }} --skip-webdriver-menu --skip-update-check --no-logo --disable-progress-bar
            echo -e "\nKey:" >> $GITHUB_STEP_SUMMARY
            cat ./*KEYS.txt >> $GITHUB_STEP_SUMMARY
          fi

  macOS:
    runs-on: macos-latest
    steps:
      - name: Generate key on macOS
        run: |
          ACCOUNT=0
          KEY=2
          MAIL=emailfake
          KEY_TYPE=--key
          BRANCH=main

          git clone -b ${BRANCH} https://github.com/373262/EKey.git
          cd EKey

          brew install python
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

          if [[ ${ACCOUNT} -ne 0 && ${KEY} -ne 0 ]]; then
            seq 1 ${ACCOUNT} | xargs -I {} -P ${ACCOUNT} python3 tgram.py --silent --chrome --account --email-api ${MAIL} --vktoken ${{ secrets.VKTOKEN }} --vktoken2 ${{ secrets.VKTOKEN2 }} --vkgroupid ${{ secrets.VKGROUPID }} --token ${{ secrets.TOKEN }} --skip-webdriver-menu --skip-update-check --no-logo --disable-progress-bar &
            seq 1 ${KEY} | xargs -I {} -P ${KEY} python3 tgram.py --chrome --key --email-api ${MAIL} --skip-webdriver-menu --skip-update-check --no-logo --disable-progress-bar
            wait
            echo "Account:" >> $GITHUB_STEP_SUMMARY
            cat ./*ACCOUNTS.txt >> $GITHUB_STEP_SUMMARY
            echo -e "\nKey:" >> $GITHUB_STEP_SUMMARY
            cat ./*KEYS.txt >> $GITHUB_STEP_SUMMARY
          elif [[ ${ACCOUNT} -ne 0 ]]; then
            seq 1 ${ACCOUNT} | xargs -I {} -P ${ACCOUNT} python3 tgram.py --silent --chrome --account --email-api ${MAIL} --vktoken ${{ secrets.VKTOKEN }} --vktoken2 ${{ secrets.VKTOKEN2 }} --vkgroupid ${{ secrets.VKGROUPID }} --token ${{ secrets.TOKEN }} --skip-webdriver-menu --skip-update-check --no-logo --disable-progress-bar
            echo -e "\nAccount:" >> $GITHUB_STEP_SUMMARY
            cat ./*ACCOUNTS.txt >> $GITHUB_STEP_SUMMARY
          elif [[ ${KEY} -ne 0 ]]; then
            seq 1 ${KEY} | xargs -I {} -P ${KEY} python3 tgram.py --silent --chrome --key --email-api ${MAIL} --vktoken ${{ secrets.VKTOKEN }} --vktoken2 ${{ secrets.VKTOKEN2 }} --vkgroupid ${{ secrets.VKGROUPID }} --token ${{ secrets.TOKEN }} --skip-webdriver-menu --skip-update-check --no-logo --disable-progress-bar
            echo -e "\nKey:" >> $GITHUB_STEP_SUMMARY
            cat ./*KEYS.txt >> $GITHUB_STEP_SUMMARY
          fi
